#===============================================================================
# docker-compose.yml: OpenWRT ImageBuilder for Netgear R8000 router
#
# Copyright © 2022 by Xtreme Performance Services. All rights reserved.
# Author(s): Douglas W. Lincicome <doug@xtremefabrications.com>
#
# - Quick image building guide:
#     https://openwrt.org/docs/guide-developer/toolchain/beginners-build-guide
#
# - Using the image builder:
#     https://openwrt.org/docs/guide-user/additional-software/imagebuilder
#
# - Build system usage:
#     https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem
#
#===============================================================================

services:
  make-image:
    image: openwrt/imagebuilder:${TARGET}-${SUBTARGET}-${RELEASE}
    command: ['make', '-i', '-j', 'image', "PROFILE=${PROFILE}", "PACKAGES=${PACKAGES}", "FILES=${FILES}", "BIN_DIR=${BIN_DIR}", "EXTRA_IMAGE_NAME=${EXTRA_IMAGE_NAME}", "DISABLE_SERVICES=${DISABLE_SERVICES}", "ADD_LOCAL_KEY=${ADD_LOCAL_KEY}"]
    volumes:
      - type: bind
        source: ./files
        target: ${FILES}
      - type: bind
        source: ./bin
        target: ${BIN_DIR}
